module.exports = {
  borderStyleDefault: "solid",
  borderWidthNone: 0,
  borderWidthThin: "1px",
  borderWidthThick: "2px",
  borderWidthThicker: "4px",
  borderRadiusNone: 0,
  borderRadiusSmall: "8px",
  borderRadiusPill: "500px",
  borderRadiusCircular: "50%",
  colorBrandPrimaryLightest: "rgb(238, 238, 238)",
  colorBrandPrimaryLight: "rgb(205, 205, 205)",
  colorBrandPrimaryMedium: "rgb(0, 0, 0)",
  colorBrandPrimaryDark: "rgb(0, 0, 0)",
  colorBrandPrimaryDarkest: "rgb(0, 0, 0)",
  colorBrandSecondaryLightest: "rgb(238, 238, 238)",
  colorBrandSecondaryLight: "rgb(205, 205, 205)",
  colorBrandSecondaryMedium: "rgb(0, 0, 0)",
  colorBrandSecondaryDark: "rgb(0, 0, 0)",
  colorBrandSecondaryDarkest: "rgb(0, 0, 0)",
  colorAttentionLightest: "rgb(255, 217, 191)",
  colorAttentionLight: "rgb(255, 161, 96)",
  colorAttentionMedium: "rgb(255, 109, 0)",
  colorAttentionDark: "rgb(224, 88, 0)",
  colorAttentionDarkest: "rgb(194, 67, 0)",
  colorSuccessLightest: "rgb(191, 255, 210)",
  colorSuccessLight: "rgb(96, 243, 145)",
  colorSuccessMedium: "rgb(0, 200, 83)",
  colorSuccessDark: "rgb(0, 176, 72)",
  colorSuccessDarkest: "rgb(0, 152, 61)",
  colorNeutralLightest: "rgb(255, 255, 255)",
  colorNeutralLight: "rgb(240, 242, 247)",
  colorNeutralMedium: "rgb(212, 215, 221)",
  colorNeutralDark: "rgb(96, 100, 108)",
  colorNeutralDarkest: "rgb(0, 0, 0)",
  opacitySemiOpaque: "0.8",
  opacityIntense: "0.64",
  opacityMedium: "0.32",
  opacityLight: "0.16",
  opacitySemiTransparent: "0.08",
  shadowOffsetXNone: 0,
  shadowOffsetYLevel1: "4px",
  shadowOffsetYLevel2: "8px",
  shadowOffsetYLevel3: "16px",
  shadowOffsetYLevel4: "24px",
  shadowBlurRadiusLevel1: "16px",
  shadowBlurRadiusLevel2: "24px",
  shadowBlurRadiusLevel3: "32px",
  shadowBlurRadiusLevel4: "48px",
  shadowSpreadRadiusDefault: 0,
  spacingInlineXxxs: "4px",
  spacingInlineXxs: "8px",
  spacingInlineXs: "16px",
  spacingInlineSm: "24px",
  spacingInlineMd: "32px",
  spacingInlineLg: "48px",
  spacingInlineXl: "64px",
  spacingInsetXxs: "4px",
  spacingInsetXs: "8px",
  spacingInsetSm: "16px",
  spacingInsetMd: "24px",
  spacingInsetLg: "32px",
  spacingInsetXl: "48px",
  spacingSquishXs: "4px 8px",
  spacingSquishSm: "8px 16px",
  spacingSquishMd: "16px 24px",
  spacingSquishLg: "16px 32px",
  spacingSquishXl: "32px 48px",
  spacingStackXxxs: "4px",
  spacingStackXxs: "8px",
  spacingStackXs: "16px",
  spacingStackSm: "24px",
  spacingStackMd: "32px",
  spacingStackLg: "48px",
  spacingStackXl: "72px",
  spacingStackXxl: "120px",
  spacingStackXxxl: "160px",
  fontFamilyHighlight: "Archivo",
  fontFamilyBase: "Archivo",
  fontLineHeightXxxs: "12px",
  fontLineHeightXxs: "16px",
  fontLineHeightXs: "20px",
  fontLineHeightSm: "24px",
  fontLineHeightMd: "28px",
  fontLineHeightLg: "32px",
  fontLineHeightXl: "36px",
  fontLineHeightXxl: "48px",
  fontLineHeightXxxl: "64px",
  fontLineHeightUl: "80px",
  fontSizeXs: "12px",
  fontSizeSm: "16px",
  fontSizeMd: "24px",
  fontSizeLg: "32px",
  fontSizeXl: "48px",
  fontSizeXxl: "64px",
  fontSizeXxxl: "80px",
  fontWeightRegular: 300,
  fontWeightMedium: 500,
  fontWeightBold: 700,
  textUnderline: "underline",
  textStrike: "line-through",
  textUppercase: "uppercase",
};